###
//CREATE new Post
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "test_post",
    "content": "test_content",
    "sender": "test_sender"
}
###
// GET all posts
GET http://localhost:3000/posts/

###
// GET post by id
GET http://localhost:3000/posts/6752a9f88e2e8f32d00cfcec

###
// GET post by sender
GET http://localhost:3000/posts?sender=test_sender

###
// UPDATE post by id
PUT http://localhost:3000/posts/6752a9f88e2e8f32d00cfcec
Content-Type: application/json

{
    "title": "test_new_title"
}

###
// DELETE post by id
DELETE http://localhost:3000/posts/6752a9f88e2e8f32d00cfcec

###
//CREATE new comment
POST http://localhost:3000/comments
Content-Type: application/json

{
    "content": "test_content",
    "author": "hila"
}

###
// GET all comments
GET http://localhost:3000/comments/

###
// GET comment by id
GET http://localhost:3000/comments/6752aa198e2e8f32d00cfcf5

###
// UPDATE comment by id
PUT http://localhost:3000/comments/6752aa198e2e8f32d00cfcf5
Content-Type: application/json

{
    "content": "test_new_content",
    "author": "idan"
}

###
// DELETE comment by id
DELETE  http://localhost:3000/comments/6752aa198e2e8f32d00cfcf5
Content-Type: application/json