###

GET http://localhost:3000

###
GET http://localhost:3000/posts

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "test_title",
    "content": "test_content",
    "owner": "bla"
}
###

GET http://localhost:3000/posts/

###