###
//CREATE new Post
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "test_post",
    "content": "test_content",
    "sender": "test_sender"
}
###
// GET all posts
GET http://localhost:3000/posts/

###
// GET post by id
GET http://localhost:3000/posts/6751deefa2829a7d55402505

###
// GET post by sender
GET http://localhost:3000/posts?sender=test_sender

###
// UPDATE post by id
PUT http://localhost:3000/posts/6751deefa2829a7d55402505
Content-Type: application/json

{
    "title": "test_title3"
}

###
//CREATE new comment
POST http://localhost:3000/comments
Content-Type: application/json

{
    "content": "test_content",
    "author": "hila"
}

###
// GET all comments
GET http://localhost:3000/comments/

###
// GET comment by id
GET http://localhost:3000/comments/6751ccd6764d3be8c8593aaa

###
// UPDATE comment by id
PUT http://localhost:3000/comments/6751e00658dd212aca28716d
Content-Type: application/json

{
    "author": "idan"
}